project_id = "fahkxnaolxvylqxmkqed"
[functions.create-transaction]
enabled = true
verify_jwt = true
import_map = "./functions/create-transaction/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-transaction/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-transaction/*.html" ]
